In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import src.models.train_model as trainer
import src.models.predict_model as predictor

# Training

## Corn

In [3]:
data_dir = "../data/processed/Corn/"

In [4]:
train_data, train_labels = trainer._load_training_data(data_dir)
eval_data, eval_labels = trainer._load_testing_data(data_dir)

In [5]:
num_classes = train_labels[0].shape[0]

In [6]:
classifier = trainer.model(num_classes)

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 256, 256, 32)      896       
_________________________________________________________________
leaky_re_lu (LeakyReLU)      (None, 256, 256, 32)      0         
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 128, 128, 32)      0         
_________________________________________________________________
dropout (Dropout)            (None, 128, 128, 32)      0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 128, 128, 64)      18496     
_________________________________________________________________
leaky_re_lu_1 (LeakyReLU)    (None, 128, 128, 64)      0         
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 64, 64, 64)        0

In [7]:
batch_size = 64
epochs = 20

In [8]:
classifier.fit(train_data, train_labels, batch_size=batch_size, epochs=epochs, validation_data=(eval_data, eval_labels))

Train on 1618 samples, validate on 405 samples
Epoch 1/20
1618/1618 [==============================] - 12s 7ms/sample - loss: 2.1136 - accuracy: 0.6446 - val_loss: 0.5286 - val_accuracy: 0.7506
Epoch 2/20
1618/1618 [==============================] - 4s 2ms/sample - loss: 0.4516 - accuracy: 0.8164 - val_loss: 0.4338 - val_accuracy: 0.8000
Epoch 3/20
1618/1618 [==============================] - 4s 2ms/sample - loss: 0.3551 - accuracy: 0.8387 - val_loss: 0.3908 - val_accuracy: 0.8469
Epoch 4/20
1618/1618 [==============================] - 4s 2ms/sample - loss: 0.2927 - accuracy: 0.8752 - val_loss: 0.3746 - val_accuracy: 0.8469
Epoch 5/20
1618/1618 [==============================] - 4s 2ms/sample - loss: 0.2620 - accuracy: 0.8789 - val_loss: 0.3398 - val_accuracy: 0.8568
Epoch 6/20
1618/1618 [==============================] - 4s 2ms/sample - loss: 0.2169 - accuracy: 0.9054 - val_loss: 0.4757 - val_accuracy: 0.8296
Epoch 7/20
1618/1618 [==============================] - 4s 2ms/sample - loss

In [9]:
classifier.save("../models/Corn.h5")

## Pepper

In [33]:
data_dir = "../data/processed/Pepper/"
train_data, train_labels = trainer._load_training_data(data_dir)
eval_data, eval_labels = trainer._load_testing_data(data_dir)
num_classes = train_labels[0].shape[0]
classifier = trainer.model(num_classes)
batch_size = 64
epochs = 20
classifier.fit(train_data, train_labels, batch_size=batch_size, epochs=epochs, validation_data=(eval_data, eval_labels))

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_3 (Conv2D)            (None, 256, 256, 32)      896       
_________________________________________________________________
leaky_re_lu_4 (LeakyReLU)    (None, 256, 256, 32)      0         
_________________________________________________________________
max_pooling2d_3 (MaxPooling2 (None, 128, 128, 32)      0         
_________________________________________________________________
dropout_4 (Dropout)          (None, 128, 128, 32)      0         
_________________________________________________________________
conv2d_4 (Conv2D)            (None, 128, 128, 64)      18496     
_________________________________________________________________
leaky_re_lu_5 (LeakyReLU)    (None, 128, 128, 64)      0         
_________________________________________________________________
max_pooling2d_4 (MaxPooling2 (None, 64, 64, 64)       

In [34]:
classifier.save("../models/Pepper.h5")

# Test

In [20]:
from tensorflow import keras

In [21]:
import numpy as np
import os

def load_testing_data(base_dir):
    """Load testing data"""
    x_test = np.load(os.path.join(base_dir, 'test_data.npy'))
    y_test = np.load(os.path.join(base_dir, 'test_labels.npy'))
    return x_test, y_test

## Corn

In [22]:
trained_model = keras.models.load_model("../models/Corn.h5")
trained_model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 256, 256, 32)      896       
_________________________________________________________________
leaky_re_lu (LeakyReLU)      (None, 256, 256, 32)      0         
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 128, 128, 32)      0         
_________________________________________________________________
dropout (Dropout)            (None, 128, 128, 32)      0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 128, 128, 64)      18496     
_________________________________________________________________
leaky_re_lu_1 (LeakyReLU)    (None, 128, 128, 64)      0         
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 64, 64, 64)        0

In [23]:
test_images, test_labels = load_testing_data("../data/processed/Corn/")

In [14]:
loss, acc = trained_model.evaluate(test_images, test_labels, verbose=2)

506/1 - 1s - loss: 0.2087 - accuracy: 0.9012


In [15]:
# the old model
trained_model = keras.models.load_model("../models/corn.h5")
trained_model.summary()
test_images, test_labels = load_testing_data("../data/processed/Corn/")
loss, acc = trained_model.evaluate(test_images, test_labels, verbose=2)

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 256, 256, 32)      896       
_________________________________________________________________
leaky_re_lu (LeakyReLU)      (None, 256, 256, 32)      0         
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 128, 128, 32)      0         
_________________________________________________________________
dropout (Dropout)            (None, 128, 128, 32)      0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 128, 128, 64)      18496     
_________________________________________________________________
leaky_re_lu_1 (LeakyReLU)    (None, 128, 128, 64)      0         
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 64, 64, 64)        0

In [19]:
predictions = trained_model.predict(test_images)

In [40]:
keras.utils.to_categorical(np.argmax(predictions[500], axis=0), 4)

array([0., 0., 1., 0.], dtype=float32)

In [41]:
test_labels[500]

array([0., 0., 1., 0.], dtype=float32)

In [37]:
len(test_labels)

506

## Pepper

In [36]:
trained_model = keras.models.load_model("../models/Pepper.h5")

In [38]:
trained_model

In [39]:
trained_model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_3 (Conv2D)            (None, 256, 256, 32)      896       
_________________________________________________________________
leaky_re_lu_4 (LeakyReLU)    (None, 256, 256, 32)      0         
_________________________________________________________________
max_pooling2d_3 (MaxPooling2 (None, 128, 128, 32)      0         
_________________________________________________________________
dropout_4 (Dropout)          (None, 128, 128, 32)      0         
_________________________________________________________________
conv2d_4 (Conv2D)            (None, 128, 128, 64)      18496     
_________________________________________________________________
leaky_re_lu_5 (LeakyReLU)    (None, 128, 128, 64)      0         
_________________________________________________________________
max_pooling2d_4 (MaxPooling2 (None, 64, 64, 64)       

In [45]:
test_images, test_labels = load_testing_data("../data/processed/Pepper/")

In [47]:
loss, acc = trained_model.evaluate(test_images, test_labels, verbose=2)

495/1 - 1s - loss: 0.0518 - accuracy: 0.9737


# Predictor

In [13]:
model = predictor.load_model("../models/Corn.h5")

In [14]:
classes = predictor.get_classes("../data/processed/Corn/Corn_(maize)-labels.json")

In [15]:
classes

{'0': 'Cercospora_leaf_spot Gray_leaf_spot',
 '1': 'Common_rust_',
 '2': 'Northern_Leaf_Blight',
 '3': 'healthy'}

In [16]:
from src.data.image_processing import preprocess_image

In [17]:
data = preprocess_image("../1621.JPG")

In [18]:
data.shape

(256, 256, 3)

In [25]:
test_images.shape

(506, 256, 256, 3)

In [26]:
test_images[0].shape

(256, 256, 3)

In [27]:
model.predict(test_images)

array([[1.2587336e-08, 1.0000000e+00, 8.0318904e-11, 5.0162275e-12],
       [1.8874422e-09, 1.0000000e+00, 2.4954841e-10, 4.7703425e-11],
       [1.6879438e-09, 1.0000000e+00, 8.8894689e-16, 1.1405301e-14],
       ...,
       [1.5167467e-05, 9.0588871e-03, 9.8807305e-01, 2.8528438e-03],
       [9.9978584e-01, 5.2795771e-12, 2.1415771e-04, 2.5801851e-13],
       [2.6522891e-09, 1.0000000e+00, 1.2610921e-10, 8.1634916e-12]],
      dtype=float32)

In [32]:
prediction = model.predict(np.array([data]))

In [41]:
classes[np.argmax(prediction, axis=1)[0]]

KeyError: 1

In [42]:
classes

{'0': 'Cercospora_leaf_spot Gray_leaf_spot',
 '1': 'Common_rust_',
 '2': 'Northern_Leaf_Blight',
 '3': 'healthy'}